### PR TITLE
Create FR.json file french traductions

### PR DESCRIPTION
**Pull request by Piarre**
Dashboard is not very translatable

### CODE REVIEW

**Comment by Piarre** [comment]
French site traduction

**Comment by Piarre** [comment]
French trad

**Comment by Lunac-dev** [comment]
Thanks. Can you translate the Lite version as well?

**Comment by Piarre** [comment]
What is the "Lite version" ?

**Comment by Lunac-dev** [comment]
[This](https://github.com/Lunac-dev/valorant-store-checker-lite)

**Comment by Piarre** [comment]
Ok thanks, I'll do it tonight

**Comment by Piarre** [comment]
You hadn't authorize this pull request.

**Pull request merged**
